#!/bin/bash
clang -O2 *.c glad/src/gl.c triangulator/*.c wavefront_object_reader/*.c wavefront_object_reader/wavefront_object_definition/*.c libft/src/*.c vector/*.c -Ivector -Iglad/include -Iwavefront_object_reader/ -Ilibft/inc -Itriangulator `pkg-config --cflags --libs --static glfw3` -o program
