#!/bin/bash
rm -rf program program.dSym && 
clang -g -O0 -fsanitize=address *.c triangulator/*.c wavefront_object_reader/*.c wavefront_object_reader/wavefront_object_definition/*.c libft/src/*.c vector/*.c -Ivector -Iwavefront_object_reader/ -Ilibft/inc -Itriangulator `pkg-config --cflags --libs --static glfw3` -framework OpenGL -framework Cocoa -lSDL2 -lSDL2_image -I/usr/include/SDL2 -o program
