#!/bin/bash
rm -rf program program.dSym && clear &&
clang -Wall -Wextra -O2 *.c triangulator/*.c wavefront_object_reader/*.c wavefront_object_reader/wavefront_object_definition/*.c minilib/src/*.c vector/*.c -Ivector -Iwavefront_object_reader/ -Iminilib/inc -Itriangulator `pkg-config --cflags --libs --static glfw3` -framework OpenGL -framework Cocoa -lSDL2 -lSDL2_image -I/usr/include/SDL2 -o program
