#!/bin/bash
rm -rf program program.dSym && clear &&
clang -Wall -Wextra -g -O0 -fsanitize=address *.c ../triangulator/*.c ../wavefront_object_reader/*.c ../wavefront_object_reader/wavefront_object_definition/*.c ../minilib/src/*.c ../vector/*.c -I../vector -I../wavefront_object_reader/ -I../minilib/inc -I../triangulator `pkg-config --cflags --libs --static glfw3` -framework OpenGL -framework Cocoa -lSDL2 -lSDL2_image -I/usr/include/SDL2 -o program
